services:
  ocr:
    #image: techblog/ocr-docker:latest
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: ocr-docker
    labels:
      - "com.ouroboros.enable=true"
    networks:
      - default
    restart: unless-stopped
